# JVM Settings
org.gradle.jvmargs=-Xmx2048M

# Minecraft Settings
minecraft_version=1.21.1

# Enabled Platforms
enabled_platforms=fabric,neoforge

# Mod Information
archives_base_name=farm_and_charm
mod_version=1.1.23
maven_group=net.satisfy.farm_and_charm

# Architectury Dependencies
architectury_version=13.0.8

# Mod Dependencies
rei_version=16.0.799
jei_version=19.22.0.315
terraform_wood_api_version=11.0.0-alpha.1
mod_menu_version=11.0.3

# Platform Versions
fabric_loader_version=0.17.2
fabric_api_version=0.116.6+1.21.1
neoforge_version=21.1.205
cloth_fabric_version=11.1.136